packages:
  - apps/*
  - packages/*
  - packages/eslint/*
  - packages/eslint-presets/*
  - packages/prettier/*
catalog:
  '@types/node': 22.15.21
  '@total-typescript/ts-reset': 0.6.1
  prettier: 3.5.3
  typescript: 5.8.3
  '@eslint/js': 9.27.0
  eslint: 9.27.0
  'eslint-config-prettier': 10.1.5
  'eslint-plugin-import-x': 4.13.1
  globals: 16.2.0
  vitest: 3.1.4
  tsup: 8.5.0
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
